# Generated by Django 6.0 on 2025-12-16 07:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadSession",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "CREATED"),
                            ("presigned", "PRESIGNED"),
                            ("completed", "COMPLETED"),
                            ("failed", "FAILED"),
                        ],
                        default="created",
                        max_length=32,
                    ),
                ),
                ("purpose", models.CharField(blank=True, default="", max_length=256)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upload_sessions",
                        to="user.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("storage_provider", models.CharField(max_length=32)),
                ("storage_key", models.CharField(max_length=512)),
                ("mime_type", models.CharField(max_length=127)),
                ("byte_size", models.BigIntegerField()),
                ("checksum", models.CharField(blank=True, max_length=128, null=True)),
                ("exif_data", models.JSONField(blank=True, null=True)),
                ("exif_captured_at", models.DateTimeField(blank=True, null=True)),
                (
                    "upload_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assets",
                        to="asset.uploadsession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssetRef",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("owner_id", models.UUIDField()),
                ("role", models.CharField(blank=True, default="", max_length=64)),
                ("ordering", models.IntegerField(default=0)),
                ("captured_at", models.DateTimeField(blank=True, null=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refs",
                        to="asset.asset",
                    ),
                ),
                (
                    "owner_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["owner_content_type", "owner_id"],
                        name="asset_asset_owner_c_350290_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="asset_asset_created_62a465_idx"
                    ),
                    models.Index(
                        fields=["captured_at"], name="asset_asset_capture_65d292_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="uploadsession",
            index=models.Index(
                fields=["client", "created_at"], name="asset_uploa_client__614339_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="uploadsession",
            index=models.Index(fields=["status"], name="asset_uploa_status_254ad2_idx"),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["storage_provider", "storage_key"],
                name="asset_asset_storage_7bca39_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["checksum"], name="asset_asset_checksu_591e99_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["created_at"], name="asset_asset_created_839fef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["exif_captured_at"], name="asset_asset_exif_ca_eae4c4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["is_active"], name="asset_asset_is_acti_d69c24_idx"
            ),
        ),
    ]
